models/Post.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "post".
 *
 * @property int $id
 * @property int $id_user Пользователь
 * @property string $text Текст поста
 * @property int $cat Раздел
 * @property int $like Лайк
 * @property int $dislike Дизлайк
 */
class Post extends \yii\db\ActiveRecord
{

    public $images; //Переменая для изображения
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'post';
    }

    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }


    public function getComment() {
        return $this->hasMany(Comment::className(), ['id_post' => 'id'])->orderBy('date DESC')->limit(1);
    }

    public function getAllcomments(){
        return $this->hasMany(Comment::className(), ['id_post' => 'id'])->orderBy('date DESC');
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_user', 'text'], 'required'],
            [['cat', 'like', 'dislike','date', 'magnet', 'vk_id'], 'safe'],
            [['id_user', 'cat', 'like', 'dislike'], 'integer'],
            [['text', 'magnet'], 'string'],
            [['images'], 'image', 'extensions' => 'png, jpg, jpeg, gif', 'skipOnEmpty' => true, 'maxFiles' => 10, 'maxWidth' => 1920, 'maxHeight' => 1080],
        ];
    }

    public function getAuthor() {
        return $this->hasOne(User::className(), ['id' => 'id_user']);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            /*'id' => 'ID',*/
            'id_user' => 'Пользователь',
            'text' => 'Текст поста',
            'cat' => 'Закрепить пост',
            'like' => 'Лайк',
            'dislike' => 'Дизлайк',
            'images' => 'Изображения',
            'magnet' => 'magnet ссылка',
        ];
    }

    /*
    * Загрузка нескольких картинок
    */
    public function uploadGallery()
    {
        if ( $this->validate() )
        {
            foreach ($this->images as $file)
            {
                $path = 'img/store' . $file->baseName . '.' . $file->extension;
                $file->saveAs($path);
                $this->attachImage($path, false);
                @unlink($path);
            }
            return true;
        }
        else
        {
            return false;
        }
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use app\models\Comment;
use app\models\Ocenka;
use Yii;
use app\models\Post;
use app\models\PostSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\controllers\CastomController;
use app\models\User;
use yii\web\UploadedFile;
use yii\web\Response;
use rico\yii2images\models\Image;
use yii\web\HttpException;

/**
 * PostController implements the CRUD actions for Post model.
 */
class PostController extends CastomController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    /*[
                        // неавторизованному пользователю доступны только эти действия
                        'actions' => ['login', 'registration'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],*/
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'comment-create', 'com', 'del-com', 'edit-comment', 'like', 'dislike', 'del-img', 'all-comment', 'hidden-comment', 'count-comment',
                        'all-text', 'hidden-text'],
                        'allow' => true,
                        'roles' => ['user'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    /**
     * Lists all Post models.
     * @return mixed
     */
    public function actionIndex()
    {

        $this->setMeta('CFW');
        $user = User::find()->where(['id' => Yii::$app->user->id])->one();

        $searchModel = new PostSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'user' => $user,
        ]);
    }

    public function actionCommentCreate($text, $id_user, $id_user_otv, $id){

        $model = new Comment();
        $model->id_post = $id;
        $model->id_user = $id_user;
        $model->id_user_otv = $id_user_otv;

        /*$text = preg_replace('/(^|\s+)@([0-9a-zA-Zа-яА-Я]+)(\b|$)/', '$1<a href="#$2">@$2</a>', $text);*/
       /* $text = preg_replace('/(^|\s+)#([0-9a-zA-Zа-яА-Я]+)(\b|$)/', '$1<a href="#$2">#$2</a>', $text);*/

        $model->text = $text;
        if($model->save()){
            $this->layout = false;
            return $this->render('comment', [
                'model' => $model,
            ]);
        }else{
            return  $model->errors;
        }
        //$model->save();

        ///return $id;
    }

    public function actionCom($id){

        $model = Comment::find()->where(['id'=>$id])->one();
        if($model->id_user  == Yii::$app->user->id || Yii::$app->user->can('redactor')) {
            $array = array();
            $array['text'] = $model->text;
            $array['id_user_otv'] = $model->id_user_otv;
            $array['date'] = $model->date;
            $array['id'] = $model->id;
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $array;
        }else{
            throw new HttpException(404, 'Доступ запрещён!');
        }
    }

    public function actionDelCom($id){
        $model = Comment::find()->where(['id' => $id])->one();
        if($model->id_user  == Yii::$app->user->id || Yii::$app->user->can('redactor')){
            $model->delete();
            return 'ok';
        }else {
            throw new HttpException(404, 'Доступ запрещён!');
        }
    }

    public function actionEditComment($text,$id, $user = null, $date){
        $model = Comment::find()->where(['id' => $id])->one();
        if($model->id_user  == Yii::$app->user->id || Yii::$app->user->can('redactor')){
            $model->text = $text;
            $model->date = $date;
            if($user != 0){
                $model->id_user_otv = $user;
            }
            if($model->save()){
                $this->layout = false;
                return CastomController::namea($model->text, $model->id_user_otv);
            }else{
                return  $model->errors;
            }
        }else{
            throw new HttpException(404, 'Доступ запрещён!');
        }
    }

    public function actionLike($id){
       /* $model = Post::find()->where(['id' => $id])->one();
        $model->like +=1;
        $model->save();
        return $model->like;*/

       $proverka = Ocenka::find()->where(['id_post' => $id])->andWhere(['id_user' => Yii::$app->user->id])->andWhere(['like' => 1])->one();

       if(!$proverka){
           $model = new Ocenka();
           $model->id_post = $id;
           $model->id_user = Yii::$app->user->id;
           $model->like = 1;
           $model->save();
           $model1 = Post::find()->where(['id' => $id])->one();
           $model1->like +=1;
           $model1->save();
           return $model1->like;
       }
       else {
           return false;
       }
    }

    public function actionDislike($id){
        /*$model = Post::find()->where(['id' => $id])->one();
        $model->dislike +=1;
        $model->save();
        return $model->dislike;*/

        $proverka = Ocenka::find()->where(['id_post' => $id])->andWhere(['id_user' => Yii::$app->user->id])->andWhere(['dislike' => 1])->one();

        if(!$proverka){
            $model = new Ocenka();
            $model->id_post = $id;
            $model->id_user = Yii::$app->user->id;
            $model->dislike = 1;
            $model->save();
            $model1 = Post::find()->where(['id' => $id])->one();
            $model1->dislike +=1;
            $model1->save();
            return $model1->dislike;
        }
        else {
            return false;
        }
    }

    public function actionDelImg($id, $img = null)
    {
        $model = $this->findModel($id);
        if($model->id_user  == Yii::$app->user->id || Yii::$app->user->can('redactor')){
            if ( $img !== null && ($image = Image::findOne($img)) !== null) {

                $model->removeImage( $image );
            }
            if (!$im = Image::find()->where(['itemId' => $id])->all())
            {
                return 'ok';
            }

            /*Устанавливаем главную картинку если мы ее удалили*/


            foreach ($model->getImages() as $imeges)
            {
                $model->setMainImage($imeges);
                break;
            }

            return 'ok';
        }else{
            throw new HttpException(404, 'Доступ запрещён!');
        }
    }


    public function actionAllComment($id){
        $models = Comment::find()->where(['id_post' => $id])->all();
        $this->layout = false;
        return $this->render('allcomment', compact('models'));
    }

    public function actionHiddenComment($id){
        $comment = $this->findModel($id);
        $models = $comment->comment;
        $this->layout = false;
        return $this->render('allcomment', compact('models'));
    }

    public function actionCountComment($id){
        $model = $this->findModel($id);
        return count($model->allcomments);
    }


    /**
     * Displays a single Post model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Post model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Post();
        $this->setMeta('Создать пост');
        if ($model->load(Yii::$app->request->post())) {

            $model->id_user = Yii::$app->user->id;
            /*if(Yii::$app->user->can('user')){
                $model->cat = 0;
            }*/
            $model->save();
            $model->images = UploadedFile::getInstances($model, 'images');
            if( $model->images )
            {
                $model->uploadGallery();
            }
            return $this->redirect(['post/index']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Post model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {

        $model = $this->findModel($id);
        if($model->id_user  == Yii::$app->user->id || Yii::$app->user->can('redactor')){
            $this->setMeta('Редактировать пост');

            if ($model->load(Yii::$app->request->post())) {

                $model->save();

                $model->images = UploadedFile::getInstances($model, 'images');
                if( $model->images )
                {
                    $model->uploadGallery();
                }

                return $this->redirect(['post/index']);
            }

            return $this->render('update', [
                'model' => $model,
            ]);
        }else{
            throw new HttpException(404, 'Доступ запрещён!');
        }
    }

    /**
     * Deletes an existing Post model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {

        $model = $this->findModel($id);

views/post/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\tinymce\TinyMce;

/* @var $this yii\web\View */
/* @var $model app\models\Post */
/* @var $form yii\widgets\ActiveForm */
?>
<!--<script>
    tinymce.init({
        menubar:false,
        statusbar: false,
    });
</script>-->
<div class="post-form">

    <?php $form = ActiveForm::begin(); ?>





    <?= $form->field($model, 'text')->widget(TinyMce::className(), [
        'options' => ['rows' => 16],
        'language' => 'ru',

        'clientOptions' => [
            'menubar' => false,
            'statusbar' => false,
            'plugins' => [
                "advlist autolink lists link charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table contextmenu paste image",
            ],
            'toolbar' => "styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",

            'image_dimensions' =>  false,
        ]
    ]);?>

    <?= $form->field($model, 'images[]')->fileInput(['multiple' => true, 'accept' => 'image/*']) ?>

    <?= $form->field($model, 'magnet')->textInput(['maxlength' => true]) ?>


    <?php if(Yii::$app->user->can('redactor')):?>
    <?php $model->cat = 0; ?>
        <?= $form->field($model, 'cat')
            ->radioList(['0' => 'Нет', '1' => 'Да']) ?>
    <?php endif; ?>









    <?php $gal = $model->getImages();//var_dump($gal)?>

    <?php if (!$model->isNewRecord && $model->getImages() != null) : ?>
        <div class="row">


            <?php  foreach ($gal as $file) :?>

                <div class="col-sm-4 col-md-2 col-lg-2 del_<?=$file->id?>">
                    <a href="#" class="thumbnail">
                        <?= Html::img("{$file->getUrl('150x150')}")?>
                        <span><i class="fa fa-times-circle del fa-lg delFoto" data-id="<?= $model->id ?>" data-img = "<?= $file->id ?>"></i></span>
                    </a>
                </div>

            <?php endforeach; ?>
        </div>
    <?php endif; ?>



    <div class="form-group">
        <?= Html::submitButton('Добавить пост', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/_list.php
<?php
/**
 * Created by PhpStorm.
 * User: iimikhalev
 * Date: 25.02.2019
 * Time: 13:04
 */

use yii\helpers\Url;
use app\controllers\CastomController;
use app\models\Comment;


?>

<div class="post-content">

    <!--Post Date-->
    <div class="post-date">

    </div><!--Post Date End-->
    <?php $gal = $model->getImages();//var_dump($gal)
        $count = count($gal)
    ?>

    <?php if($count > 1) :?>
    <div class="grid">
        <div class="grid-sizer"></div>
        <?php  foreach ($gal as $file) :?>

            <div class="grid-item">
                <a data-fancybox="gallery" class="gal" href="<?= Url::to($file->getUrl())?>">
                    <img class="img-responsive img-gallary post-image" src="<?= Url::to($file->getUrl())?>" alt="">
                </a>
            </div>
        <?php endforeach; ?>
    </div>

    <?php elseif($count == 1) :?>
        <?php  foreach ($gal as $file) :?>
            <a data-fancybox="gallery" class="gal" href="<?= Url::to($file->getUrl())?>">
                <img class="img-responsive img-gallary post-image" src="<?= Url::to($file->getUrl())?>" alt="">
            </a>
        <?php endforeach; ?>
    <?php endif;?>


    <!--<img src="http://placehold.it/1920x1280" alt="post-image" class="img-responsive post-image" />-->
    <!---->
    <div class="post-container foc_<?= $model->id ?>">


        <!--<img src="http://placehold.it/300x300" alt="user" class="profile-photo-md pull-left" />-->
        <?php $img = $model->author->getImage();?>
        <?php if($img != null) :?>
            <img src="<?= $img->getUrl('300x300') ?>" alt="<?= $model->author->username ?>" class="profile-photo-md pull-left" />
        <?php else :?>
            <img src="http://placehold.it/300x300" alt="<?= $model->author->username ?>" class="profile-photo-md pull-left" />
        <?php endif; ?>
        <div class="post-detail">
            <div class="user-info">
                <h5>
                    <a href="<?= Url::to(['/user/lk', 'id' => $model->author->id]) ?>" class="profile-link">
                        <?php $role = CastomController::currentUserRoleIs($model->author->id); ?>
                        <?php if($role == 'moder' || $role == 'redactor' || $role == 'admin') :?>
                            Custom Nintendo
                        <?php else :?>
                            <?=$model->author->username ?>
                        <?php endif;?>


                    </a>
                </h5>

                <p class="text-muted">Опубликованно: <?= $model->date ?></p>
            </div>
            <div class="reaction">

                <a class="btn text-green jslike"  data-id="<?= $model->id ?>"><i class="icon ion-thumbsup"></i> <?= $model->like ?></a>
                <a class="btn text-red jsdislike" data-id="<?= $model->id ?>"><i class="fa fa-thumbs-down"></i> <?= $model->dislike ?></a>
                <?php if(Yii::$app->user->can('redactor') ||
                    $model->id_user == Yii::$app->user->id) :?>

                    <a href="<?= Url::to(['/post/update', 'id' => $model->id]) ?>" class="btn text-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                    <a href="<?= Url::to(['/post/delete', 'id' => $model->id]) ?>" class="btn text-danger"><i class="fa fa-trash" aria-hidden="true"></i></a>
                <?php endif; ?>
            </div>
            <div class="line-divider"></div>
            <div class="post-text text_<?=$model->id?>" >



                <?php /*if(CastomController::countStr($model->text) > 1050):*/?><!--
                <p class="text_<?/*=$model->id*/?>"><?/*= CastomController::heh(CastomController::substr_close_tags($model->text, 20), $model->id_user)*/?></p>

                --><?php /*else :*/?>
                    <p><?= CastomController::heh($model->text, $model->id_user)?></p>
               <!-- --><?php /*endif; */?>
                <?php if($model->magnet != ''){
                    echo '<p><a href="'.$model->magnet .'">magnet ссылка</a></p>';
                } ?>

            </div>






            <div class="line-divider"></div>
            <div class="c_<?= $model->id?>">
            <?php $moments = $model->comment?>
            <?php foreach ($moments as $comment) :?>
                <div class="post-comment post-comment_<?=$comment->id ?>">
                    <?php $img =$comment->author->getImage();?>
                    <?php if(isset($img)) :?>
                        <img src="<?= $img->getUrl('300x300') ?>" alt="<?= $comment->author->username ?>" class="profile-photo-sm" />
                    <?php else :?>
                        <img src="http://placehold.it/300x300" alt="<?= $comment->author->username ?>" class="profile-photo-sm" />
                    <?php endif; ?>
                    <p><a href="<?= Url::to(['/user/lk', 'id' => $comment->id_user]) ?>" class="profile-link "><?= $comment->author->username ?></a>
                    <p class="com_<?=$comment->id ?>">&nbsp; &nbsp;
                        <?=CastomController::namea($comment->text, $comment->id_user) ?>
                    </p>
                    <!--</p>-->
                    <a href="#" class="btn text-primary com-com"  data-com="<?= $model->id?>" data-username="<?= $comment->author->username ?>" data-user="<?= $comment->id_user ?>"><i class="fa fa-comments" aria-hidden="true"></i></a>
                    <?php if($comment->id_user == Yii::$app->user->id || Yii::$app->user->can('redactor')) :?>
                        <a href="#" class="btn text-primary edit t-e_<?=$comment->id?>" data-id="<?=$comment->id?>"  data-post="<?=$model->id?>"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                        <a href="#" class="btn text-danger delitecom del-com_<?=$comment->id?>" data-id="<?=$comment->id?>"><i class="fa fa-trash" aria-hidden="true" ></i></a>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>

            </div>

            <div class="pull-right">
                <?php /*if(CastomController::countStr($model->text) > 300):*/?><!--
                <p><a href="#" class="all-text" data-id="<?/*=$model->id*/?>">Показать полностью</a></p>
                --><?php /*endif; */?>
                <?php $comCount = count($model->allcomments); if($comCount >= 2 ) : ?>
                <p><a href="#" class="all-comments" data-id="<?=$model->id?>">Все комментарии (<?= $comCount ?>)</a></p>
                <?php endif; ?>
            </div>
            <div class="post-comment">
                <?php /*$avatar = CastomController::getUserImg(); if($avatar != null) :*/?><!--
                    <img src="<?/*= $avatar */?>" alt="<?/*= $model->author->username */?>" class="profile-photo-sm" />
                <?php /*else :*/?>
                    <img src="http://placehold.it/300x300" alt="<?/*= $model->author->username */?>" class="profile-photo-sm" />
                --><?php /*endif; */?>
                   <!-- <img src="http://placehold.it/300x300" alt="" class="profile-photo-sm" />-->
                    <textarea name="text" class="form-control t_<?=$model->id?> emodje_<?= $model->id?> test"  placeholder="Комментарий" cols="30" rows="10" wrap="hard"></textarea>
                    <input type="hidden" name="id_user" class="form-control u_<?=$model->id?>" placeholder="Комментарий"  value="<?= Yii::$app->user->id ?>">
                    <input type="hidden" name="id_user_otv" class="form-control u_o_<?=$model->id?>"  placeholder="Комментарий" value="0" >
                    <input type="hidden" name="id" class="form-control id_com_<?=$model->id?>"  placeholder="Комментарий" value="" >
                    <input type="hidden" name="date" class="form-control date_<?=$model->id?>"  placeholder="Комментарий" value="" >
                    <button class="btn btn-link emo hidden-xs hidden-sm" data-id="<?=$model->id?>">
                        <i class="fa fa-smile-o" aria-hidden="true"></i>
                    </button>
                    <button class="btn btn-link com-tol btn_<?=$model->id?>" data-post="<?=$model->id?>">
                        <i class="fa fa-comment-o" aria-hidden="true"></i>
                    </button>
            </div>
        </div>
    </div>
</div>

views/post/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PostSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'id_user') ?>

    <?= $form->field($model, 'text') ?>

    <?= $form->field($model, 'cat') ?>

    <?= $form->field($model, 'like') ?>

    <?php // echo $form->field($model, 'dislike') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/post/allcomment.php
<?php
/**
 * Created by PhpStorm.
 * User: iimikhalev
 * Date: 27.02.2019
 * Time: 14:00
 */
use yii\helpers\Url;
use app\controllers\CastomController;
?>
<?php foreach ($models as $model) :?>
    <div class="post-comment post-comment_<?=$model->id ?>">
        <?php $img = $model->author->getImage();?>
        <?php if(isset($img)) :?>
            <img src="<?= $img->getUrl('300x300') ?>" alt="<?= $model->author->username ?>" class="profile-photo-sm" />
        <?php else :?>
            <img src="http://placehold.it/300x300" alt="<?= $model->author->username ?>" class="profile-photo-sm" />
        <?php endif; ?>

        <p><a href="<?= Url::to(['/user/lk', 'id' => $model->author->id]) ?>" class="profile-link"><?= $model->author->username ?> </a>
        <p class="com_<?=$model->id ?>">&nbsp; &nbsp;
             <?=CastomController::namea($model->text, $model->author->id) ?>
        </p>
        <a href="#" class="btn text-primary com-com"  data-com="<?= $model->id_post?>" data-username="<?= $model->author->username ?>" data-user="<?= $model->author->id ?>"><i class="fa fa-comments" aria-hidden="true"></i></a>
        <?php if(Yii::$app->user->can('redactor') ||
            $model->id_user == Yii::$app->user->id) :?>

            <a href="#" class="btn text-primary edit t-e_<?=$model->id?>" data-id="<?=$model->id?>"  data-post="<?=$model->id_post?>"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
            <a href="#" class="btn text-danger delitecom del-com_<?=$model->id?>" data-id="<?=$model->id?>"><i class="fa fa-trash" aria-hidden="true" ></i></a>
        <?php endif; ?>
    </div>

<?php endforeach; ?>

views/post/comment.php
<?php
/**
 * Created by PhpStorm.
 * User: iimikhalev
 * Date: 27.02.2019
 * Time: 13:34
 */

use yii\helpers\Url;
use app\controllers\CastomController;
?>

<div class="post-comment post-comment_<?=$model->id ?>"">
    <?php $img = $model->author->getImage();?>
    <?php if(isset($img)) :?>
        <img src="<?= $img->getUrl('300x300') ?>" alt="<?= $model->author->username ?>" class="profile-photo-sm" />
    <?php else :?>
        <img src="http://placehold.it/300x300" alt="<?= $model->author->username ?>" class="profile-photo-sm" />
    <?php endif; ?>
    <p><a href="<?= Url::to(['/user/lk', 'id' => $model->author->id]) ?>" class="profile-link"><?= $model->author->username ?> </a>
    <p class="com_<?=$model->id ?>">&nbsp; &nbsp;
         <?=CastomController::namea($model->text, $model->author->id) ?>
    </p>
    <a href="#" class="btn text-primary com-com"  data-com="<?= $model->id_post?>" data-username="<?= $model->author->username ?>"  data-user="<?= $model->author->id ?>"><i class="fa fa-comments" aria-hidden="true"></i></a>
    <?php if(Yii::$app->user->can('redactor') ||
        $model->id_user == Yii::$app->user->id) :?>

        <a href="#" class="btn text-primary edit t-e_<?=$model->id?>" data-id="<?=$model->id?>"  data-post="<?=$model->id_post?>"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
        <a href="#" class="btn text-danger delitecom del-com_<?=$model->id?>" data-id="<?=$model->id?>"><i class="fa fa-trash" aria-hidden="true"></i></a>
    <?php endif; ?>
</div>

views/post/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

//$this->title = 'Create Post';
$this->params['breadcrumbs'][] = ['label' => 'Посты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/post/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ListView;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $searchModel app\models\GamesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

/*$this->title = 'Games';*/
$this->params['breadcrumbs'][] = $this->title;
?>


<?= ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_list',
]);?>

views/post/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

//$this->title = 'Update Post: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Посты', 'url' => ['index']];
//$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="post-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/post/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Post */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="post-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'id_user',
            'text:ntext',
            'cat',
            'like',
            'dislike',
        ],
    ]) ?>

</div>