models/User.php
<?php

namespace app\models;
use app\controllers\CastomController;
use Yii;
use \yii\db\ActiveRecord;
use \yii\web\IdentityInterface;
use yii\helpers\Html;
use yii\helpers\Url;
/*use yii\behaviors\TimestampBehavior;
use yii\db\Expression;*/

class User extends ActiveRecord  implements IdentityInterface
{
    public $rememberMe = true;
    public $_user = false;
    public $image;


    const ACTIVE_USER = 1;
    const INVITE = 1; // Обычный инвайт
    const VIP_INVITE = 2; // vip инвайт
    public $role = array(); // Используется в форме редоктирования пользователя



    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ],
            'timestamp' => [
                'class' => 'yii\behaviors\TimestampBehavior',
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                'value' => function() { return date('U');},
            ],
        ];
    }





    public static function tableName()
    {
        return 'user';
    }



    public function rules()
    {
        return [
            [['username', 'email', 'password'], 'required', 'on' => 'registration'],
            [['auth_key', 'code','active',  'rememberMe', 'invite', 'image'], 'safe', 'on' => 'registration'],
            ['password', 'match', 'pattern' => '#\d.*\d#s', 'message' => 'Пароль должен содержать минимум 2 буквы и 2 цифры.', 'on' => 'registration'],
            ['password', 'match', 'pattern' => '#[a-z].*[a-z]#is', 'message' => 'Минимум 2 буквы верхнего и нижнего регистра и 2 цифры.', 'on' => 'registration'],
            ['password', 'match', 'pattern' => '#[A-Z].*[A-Z]#is', 'message' => 'Минимум 2 буквы верхнего и нижнего регистра и 2 цифры.', 'on' => 'registration'],
            [['password'],'string', 'length' => [7, 255], 'on' => 'registration'],
            //[['username', ], 'exist', 'targetAttribute' => ['username'] ,'on' => 'registration'],

            [['active','created_at', 'updated_at', 'invite'], 'integer'],
            [['email', 'password', 'username','auth_key', 'code'], 'string', 'max' => 255],
            ['email', 'email'],

            [['email', 'password'], 'required', 'on' => 'login'],
            [['username','auth_key', 'code','active',  'rememberMe', 'invite', 'image'], 'safe', 'on' => 'login'],

            [['auth_key', 'code','active',  'rememberMe', 'invite', 'username', 'email', 'image'], 'safe', 'on' => 'edit'],
            [['image'], 'image', 'extensions' => 'png, jpg, jpeg, gif', 'skipOnEmpty' => true, 'maxWidth' => 300, 'maxHeight' => 300],
            [['role'], 'safe', 'except' => ['redactor'], 'message' => 'У пользователя должна быть минимум одна роль'],
        ];
    }

    /**
     * @return mixed
     * Отправка почты с потверждением Email
     */
    public function sendCongirmationLink()
    {
        $confirmationLinkUrl = Url::to(['site/confirmemail', 'email' => $this->email, 'code' => $this->code]);
        $confirmationLink = Html::a('Потвердите Email', $confirmationLinkUrl);

        $sendingResult = Yii::$app->mailer->compose()
            ->setFrom(Yii::$app->params['adminEmail'])
            ->setTo($this->email)
            ->setSubject('Потвердите Email')
            ->setHtmlBody('<p> Для прохождения регистрации Вам необходимо потвердить свой email</p>
            <p>'. $confirmationLink .'</p>')
            ->send();
        return $sendingResult;
    }




    public function attributeLabels()
    {
        return [
            'email' => 'Email',
            'password' => 'Пароль',
            'username' => 'Ваш Ник',
            'image' => 'Аватар',
            'rememberMe' => 'Запомни меня',
            'role' => 'Права',
            'active' => 'Статус',
            'invite' => 'Доступ к разделу игр',
        ];
    }


    public static function findIdentity($id)
    {
        return static ::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        // TODO: Implement findIdentityByAccessToken() method.
    }

    public static function findByUsername($email)
    {
        return static ::findOne(['email' => $email, 'active' => self::ACTIVE_USER]);
    }

    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
        return $this->auth_key;
    }

    public function validateAuthKey($authKey)
    {
        return $this->auth_key === $authKey;
    }

    public function validatePassword($password)
    {
        if(Yii::$app->getSecurity()->validatePassword($password, $this->password)){
            return true;
        } else {
            return false;
        }
        //return Yii::$app->security->validatePassword($password, $this->password);
    }

    /*public function validatePassword($password){
        if(is_null($this->password))
            return CastomController::printr($this->);
        return Yii::$app->getSecurity()->validatePassword($this->salt . $password, $this->password);
    }*/

    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /*public function login()
    {
        $this->scenario = 'login';


        if ($this->validate())
        {
            if ($this->rememberMe)
            {
                $cookie = $this->getUser();

                if($cookie != null){
                    $cookie->generateAuthKey();
                    $cookie->save();

                }
            }

            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600 * 24 *30 : 0);
        }
    }*/


    /*public function login()
    {
        $this->scenario = 'login';

        if ($this->validate())
        {
            if ($this->rememberMe)
            {
                $cookie = $this->getUser();
                $cookie->generateAuthKey();
                $cookie->save();
            }

            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600 * 24 *30 : 0);
        }
    }*/

    public function getUser()
    {
        if($this->_user === false)
        {
            $this->_user = $this->findByUsername($this->email);
        }

        return $this->_user;
    }

    public function getRoles(){
        $auth = Yii::$app->authManager;
        //Масив ролей пользователя
        $userRoles = $auth->getRolesByUser($this->id);
        return $userRoles;
    }

    /**
     * @return bool
     * Загрузка одного изображения
     */
    public function upload()
    {
        if ($this->validate())
        {
            $path = 'img/store' . $this->image->baseName . '.' . $this->image->extension;
            $this->image->saveAs($path);
            $this->attachImage($path, true);
            @unlink($path);
            return true;
        }
        else
        {
            //return false;
            return $this->errors;
        }
    }


}

controllers/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: Mirol
 * Date: 04.03.2019
 * Time: 16:47
 */

namespace app\controllers;
use app\models\Comment;
use app\models\Frends;
use Tests\Behat\Gherkin\Keywords\CucumberKeywordsTest;
use Yii;
use app\controllers\CastomController;
use app\models\Message;
use app\models\User;
use yii\web\UploadedFile;
use yii\web\Response;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\HttpException;
use rico\yii2images\models\Image;

class UserController extends CastomController
{


    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                /*'only' => ['logout'],*/
                'rules' => [
                    /*[
                        // неавторизованному пользователю доступны только эти действия
                        'actions' => ['login', 'registration'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],*/
                    [
                        'actions' => ['message', 'interlocutor', 'right', 'addcom', 'del-mes', 'lk', 'option', 'online', 'spisok', 'edit-mes', 'del-img', 'seve-edit-mess'],
                        'allow' => true,
                        'roles' => ['user'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    /**
     * @param $id
     * @return string|\yii\web\Response
     * Отоброжение сообщений
     */
    public function actionMessage($id)
    {

        $userName = User::find()->where(['id' => $id])->one();

        $this->setMeta($userName->username);

        $currentUserId = Yii::$app->user->identity->getId();
        $messagesQuery = Message::findMessages($currentUserId, $id);
        Message::messageStatus($id, $currentUserId);


        $model = new Message([
            /*'from' => $currentUserId,
            'to' => $id*/
        ]);

        if ($model->load(Yii::$app->request->post()))
        {

            $model->from = $currentUserId;
            $model->to = $id;
            $model->status = 0;
            $model->creatdate = date('Y-m-d H:i:s');
            $model->save();

            $model->images = UploadedFile::getInstances($model, 'images');
            if( $model->images )
            {
                $model->uploadGallery();
            }

            $model = new Message([
                /*'from' => $currentUserId,
                'to' => $id*/
            ]);
            $messagesQuery = Message::findMessages($currentUserId, $id);
            Message::messageStatus($id, $currentUserId);
            return $this->redirect(['user/message', 'id' =>$id]);
            /*if (Yii::$app->request->isPjax)
            {
                return $this->renderAjax('_message', compact('messagesQuery', 'id', 'model'));
            }*/
        }
        /*CastomController::printr(Message::messageStatus($id, $currentUserId));
        exit;*/

        return $this->render('_message', compact('messagesQuery', 'id'/*, 'interlocutors'*/, 'model', 'userName'));

    }

    /**
     * @return string
     * Отоброжение скем переписываються пользователи
     */
    public function actionInterlocutor(){

        $this->setMeta('Сообщения');
        $messageUser = Message::find()
            ->where(['from' => Yii::$app->user->id])
            ->orWhere(['to' => Yii::$app->user->id])
            /*->groupBy('from')*/
            ->all();

        $arrayUser = [];

        foreach ($messageUser as $user)
        {
            if ($user->from != Yii:: $app->user->id)
            {
                $arrayUser[] = $user->from;
            }
            if ($user->to != Yii:: $app->user->id)
            {
                $arrayUser[] = $user->to;
            }
        }

        $arrayUser = array_unique($arrayUser);

        /*CastomController::printr($arrayUser);
        exit;*/

        //Собеседники
        $interlocutors = User::find()->where(['id' => $arrayUser])->all();

       // CastomController::printr($interlocutors);
        /*exit;*/
        if (Yii::$app->request->isPjax)
        {
            return $this->renderAjax('interlocutor', compact( 'interlocutors'));
        }
        return $this->render('interlocutor', compact( 'interlocutors'));
    }

    /**
     * @param $id
     * @return bool|string
     * Вывод ajax сообщение кто написал
     */
    public function actionRight($id){
        $this->layout = false;
        $messages = Message::find()->where(['from' => $id, 'to' => Yii::$app->user->id])->andWhere(['status' => 0])->all();
       /* CastomController::printr($messages);
        exit;*/
        if($messages){
            foreach ($messages as $mes){
                Message::messageStatus($mes->from, $mes->to);
            }
            return $this->render('left', compact('messages'));
        }else {
            return 0;
        }
    }

    /**
     * @return string
     * сохронение сообщения
     */
    public function actionAddcom (){
        $formData = Yii::$app->request->post();

        $model = new Message();

        if ($model->load(Yii::$app->request->post())) {

            $model->from = Yii::$app->user->id;
            $model->to = $model->to;
            $model->status = 0;
            $model->creatdate = date('Y-m-d H:i:s');
            $model->save();

            $model->images = UploadedFile::getInstances($model, 'images');
            if ($model->images) {
                $model->uploadGallery();
            }
        }
        $this->layout = false;
        $model->sendNewMessage(Yii::$app->user->id,  $model->to,  $model->text);
        /*return
           CastomController::printr($model) ;*/
        return $this->render('right', compact('model'));
    }

    /**
     * @param $id
     * @return string
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     * Удаление сообщений
     */
    public function actionDelMes($id){

        $model = Message::findOne($id);
        if($model->from  != Yii::$app->user->id){
            throw new HttpException(404, 'Доступ запрещён!');
        }
        $model->removeImages();
        $model->delete();

        return 'ok';
    }

    /**
     * @param $id
     * @return string
     * Профиль
     */
    public function actionLk($id){

        $model = User::findOne($id);
        $this->setMeta($model->username);
        return $this->render('lk', compact('model'));
    }

    /**
     * @return string|Response
     * Опции
     */
    public function actionOption(){
        $model = User::findOne(Yii::$app->user->id);
        $model->scenario = 'edit';
        $this->setMeta('Редактировать профиль');
        if ($model->load(Yii::$app->request->post())) {
            //CastomController::printr($model);
            $model->save();
            $model->image = UploadedFile::getInstance($model, 'image');
            if( $model->image )
            {
                $model->upload();

            }
            return $this->redirect(['user/lk', 'id' => Yii::$app->user->id]);
        }

        return $this->render('option', compact('model'));
    }

    /**
     * @param $id
     * @return int
     * Проверка пользователя на онлайн
     */
    public function actionOnline($id){
        $model = User::findOne($id);
        $now = date("Y-m-d H:i:s", time());
        $lastVisit = date("Y-m-d H:i:s", strtotime('+1 min', $model->updated_at));

        if($now < $lastVisit){
            return 1;
        }else{
            return 0;
        }
    }

    /**
     * @return array
     * Проверка списка сообщений
     */
    public function actionSpisok(){

        //$array = Yii::$app->request->post('array');

        $messageUser = Message::find()
            ->where(['from' => Yii::$app->user->id])
            ->orWhere(['to' => Yii::$app->user->id])
            /*->groupBy('from')*/
            ->all();

        $arrayUser = [];

        foreach ($messageUser as $user)
        {
            if ($user->from != Yii:: $app->user->id)
            {
                $arrayUser[] = $user->from;
            }
            if ($user->to != Yii:: $app->user->id)
            {
                $arrayUser[] = $user->to;
            }
        }

        $arrayUser = array_unique($arrayUser);

        /*CastomController::printr($arrayUser);
        exit;*/

        //Собеседники
        $interlocutors = User::find()->where(['id' => $arrayUser])->all();

        $array = array();
        $i = 0;
        foreach ($interlocutors as $user){
            $img = $user->getImage();
            $array[$i]['id'] = $user->id;
            $array[$i]['name'] = $user->username;
            if($img != null){
                $array[$i]['img'] = $img->getUrl('300x300');
            }else{
                $array[$i]['img'] = 'http://placehold.it/300x300';
            }
            //$array[$i]['img'] = $img->getUrl('300x300');
            $array[$i]['message'] = Message::findLastMessage($user->id, Yii::$app->user->id)->text;
            $array[$i]['count'] = Message::countMessage($user->id, Yii::$app->user->id);
            $array[$i]['status'] = CastomController::onlineUser($user->id);
            $i++;
        }

        \Yii::$app->response->format = Response::FORMAT_JSON;
        return $array;
    }

    /**
     * @param $id
     * @return array|bool
     * Редактирование фото, наполнение модели
     */
    public function  actionEditMes($id){
        $model = Message::findOne($id);
        if($model->from  == Yii::$app->user->id || Yii::$app->user->can('redactor')){
            $gal = $model->getImages();



            $array = array();

            $array['text'] = $model->text;
            if(isset($gal)){
                foreach ($gal as $img){

views/user/js.php
<?php
/**
 * Created by PhpStorm.
 * User: Mirol
 * Date: 11.03.2019
 * Time: 21:21
 */?>


<?php
$script = <<< JS
/*function updateList() {
      $.pjax.reload({container : '#list-messages'});
    }
    setInterval(updateList, 3000);*/
    
    /**
    * Проверка на непрочитаные сообщения
    */
    function playAudio(){
        var myAudio = new Audio;
        myAudio.src = "/saund/Sound_11154.wav";
        myAudio.play();
    }
    function show()  
        {
            var id = $('.chat-message').data('id');
            //alert (id);
            $.ajax({  
                url: "/user/right",  
                cache: false, 
                data: {id:id}, 
                success: function(html){  
                    if(html){
                        
                        if(html != 0){
                            console.log(0);
                            playAudio();
                            $(".chat-message").append(anchorme(html,{
                            attributes:
                            [
                                {
                                    name:"target",
                                    value:"_blank",
                                   
                                    
                                },
                            ],
                            truncate:40
                        })); 
                        jQuery ('.mes'). scrollTop ( 9999999 );
                        }
                        
                    }
                }  
            }); 
            $('[data-fancybox="gallery"]').fancybox({
                loop: false,
                infobar : false,
                thumbs     : false,
                slideShow  : false,
                fullScreen : false,
                protect : true,
                arrows: false,
                wheel: false,
            });
        }  
        
        function online(){
        var id = $('.online').data('id');
            //alert (id);
            $.ajax({  
                url: "/user/online",  
                cache: false, 
                data: {id:id}, 
                success: function(html){  
                    if(html){
                        
                        if(html != 0){
                            $(".online").addClass('green').html('Онлайн'); 
                        //jQuery ('.mes'). scrollTop ( 9999999 );
                        }else{
                           $(".online").removeClass('green').html('Офлайн');  
                        }
                        
                    }
                }  
            }); 
          
        }  
        online();
        /**
        *  Вызывем функцию проверки непрочитаных сообщений
        */
        $(document).ready(function(){  
            //show();  
            setInterval(show,10000);
            setInterval(online,20000);
        });
    
        $('[data-fancybox="gallery"]').fancybox({
        loop: false,
        infobar : false,
        thumbs     : false,
        slideShow  : false,
        fullScreen : false,
        protect : true,
        arrows: false,
        wheel: false,
});
    function refresh(){
        /*$('.chat-item p').each(function(i,elem) {
		//alert($(elem).text());
		$(elem).html(anchorme($(elem).text()));
        });*/
        /*val = document.getElementById("input").value;
        document.getElementById("output").innerHTML = anchorme(val);*/
       var val =  $('#message-text').val();
       $('#image_preview').append(anchorme(val));
    }
      /**
      *  Отправка сообщение ajax
      */
      $( '.addMes' ).on('beforeValidate', function( e ) {
          e.preventDefault();
          e.stopImmediatePropagation();
          var userId = $('#message-to').val();
          
          var action = $('#w0').attr('action');
          var url = '';
          if(action == '/user/message?id='+userId){
              url = '/user/addcom';
          } else if(action == '/user/save-edit-mess?id='+userId){
              url = '/user/seve-edit-mess';
          }
          
          console.log( $('#w0').attr('action'));
          //console.log( new FormData( this ));
            $.ajax( {
              url: url,
              type: 'POST',
              data: new FormData( this ),
              processData: false,
              contentType: false,
              success: function(html){  
                    if(html){
                         if(action == '/user/message?id='+userId){
                                $(".chat-message").append(anchorme(html,{
                                    attributes:
                                    [
                                        {
                                            name:"target",
                                            value:"_blank",
                                           
                                            
                                        },
                                    ],
                                    truncate:40
                                })); 
                                jQuery ('.mes'). scrollTop ( 9999999 );
                                $('#message-text').val('');
                                $('#message-text').height('20');
                                $("#message-images").val(null);
                                $('#image_preview').empty();
                            } else if(action == '/user/save-edit-mess?id='+userId){
                                var idM = $('#message-id').val();
                                var response = html;
                                $('#w0').attr('action', '/user/message?id='+userId);
                                //$('.m_'+idM).empty();
                                
                                var divOpen = 
                                    '<div class="chat-item-header">'+
                                        '<h5>'+response.name+'</h5>'+
                                        '<small class="text-muted">'+
                                            '<a href="#" class="btn text-primary edit-mes" data-id="'+idM+'"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>'+
                                            '<a href="#" class="btn text-danger del-mes" data-id="'+idM+'"><i class="fa fa-trash" aria-hidden="true"></i></a>'+
                                                response.date +                                       
                                        '</small>'+
                                    '</div>'+
                                    '<p>'+response.text+'</p>';
                                var image ='';
                                var gal = response.gal;
                                if(gal){
                                    
                                      $.each(gal,function(i,elem) {
                                          
                                          image = image + '<a data-fancybox="gallery" class="gal img-responsive" href="'+elem['full']+'">'+
                                                    '<img class="img-responsive img-gallary post-image" src="'+elem['mini']+'" alt="">'+
                                                '</a>';
                                      });
                                }
                                
                                
                              
                                
                                $('.m_'+idM).html(divOpen + image);
                                
                                $('#message-text').val('');
                                $('#message-text').height('20');
                                $("#message-images").val(null);
                                $('#image_preview').empty();
                                $('#w0').attr('action', '/user/message?id='+userId);
                                
                            }
                        
                        //refresh();
                    }
                }  
            });
        return false;
      } );
      
      
      /*$( '#message-text' ).on('change', function( e ) {
          e.preventDefault();
          e.stopImmediatePropagation();
          var val = $(this).val();
          if(anchorme(val, {
                emails:false,
                urls:false,
                ips:false,
                files:false
            })){
              $('#url_preview').append(anchorme(val));
            }
           /!*$('#url_preview').append(anchorme(val));*!/
        return false;
      } );*/
      /**
      * Удаление сообщения
      */
      $(document).on('click', '.del-mes', function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            
            $.ajax({
                url: '/user/del-mes',
                data: {id:id},
                type: 'get',
                success: function (res) {
                    //alert(res);
                    if(res == 'ok'){
                        $('.mess_'+id).addClass('animated fadeOut');
                        setTimeout(function(){ $('.mess_'+id).detach();},600)
                    }
                },
                error:function (res) {
                    res = 'ошибка';
                }
            });
      });
      

    $('.chat-item p').each(function(i,elem) {
		//alert($(elem).text());
		$(elem).html(anchorme($(elem).html(),{
                            attributes:
                            [
                                {
                                    name:"target",
                                    value:"_blank",
                                                                 
                                },
                            ],
                            truncate:40
                        }));
    });
    

    //document.getElementById("input").value = initialInput;
    //refresh();

    /*anchor me*/
    
    function breakTextMes() {
    // определяем позицию курсора
    var caret = $('#message-text').getSelection().start;
    console.log(caret);
    var text = $('#message-text').val();
    console.log(text);
    // вставляем перенос строки
    $('#message-text').val(text.substring(0, caret)+(text.substring(caret)));
    // Передвигаем курсор на новую строку.
    // Обратите внимание на fix в передаче параметра позиции курсора
    // функции setCaretPosition() для браузера Opera.
    //setCaretPosition('textarea', ($.browser.opera) ? caret+2 : caret+1);
}
    
    /**
    *  Редактирование сообщения
    */
   $(document).on('click', '.edit-mes', function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            
            var userId = $('#message-to').val();
            $.ajax({
                url: '/user/edit-mes',
                data: {id:id},
                type: 'get',
                success: function (res) {
                    //alert(res);
                   var response = res;
                   $('#message-text').val(response.text).focus();
                   //breakTextMes();
                   //$('#w0').removeClass('addMes').addClass('editMes');
                   $('#message-id').val(id);
                   $('#w0').attr('action', '/user/save-edit-mess?id='+userId);
                   var gal = response.gal;
                   if(gal){
                      $.each(gal,function(i,elem) {
                        $('#image_preview').append(
                            '<div class="col-sm-4 col-md-2 col-lg-2 delIMGMes_'+i+'">'+
                                '<a href="#" class="thumbnail">'+
                                    '<img src="'+elem+'" alt="">'+
                                    '<span><i class="fa fa-times-circle del fa-lg delFoto" data-id="'+id+'" data-img="'+i+'"></i></span>'+
                                '</a>'+
                            '</div>'
                        );
                    });
                   }
                },
                error:function (res) {
                    res = 'ошибка';
                }
            });
            $(this).html('<i class="fa fa-times" aria-hidden="true"></i>');
            $(this).removeClass('edit-mes').addClass('clouse-edit');
      });
   
   
   /**
   *  отмена редактирования сообщения
    */
   $(document).on('click', '.clouse-edit', function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            var userId = $('#message-to').val();
            $(this).html('<i class="fa fa-pencil-square-o" aria-hidden="true"></i>');
            $('#message-text').val('');
            $('#message-text').height('20');
            $("#message-images").val(null);
            $('#image_preview').empty();
            $('#message-id').val('0');
            $('#w0').attr('action', '/user/message?id='+userId);
            $(this).removeClass('clouse-edit').addClass('edit-mes');
      });
      
   /**
   *  Удаление фото при редоктировании
   */
   $(document).on('click', '.delFoto', function (e) {
    e.preventDefault();
    var id = $(this).data('id');
    var img = $(this).data('img');

    $.ajax({
        url: '/user/del-img', // отпровляем в контролер Entry
        data: {id: id, img:img}, // передаём id
        type: 'GET',   // отпровляем методом get
        // если хорошо то какийты действия
        success: function (res) {
            // если пользователь попытался подменить id то выводем в сообщение
            console.log(res);
                //$('.text_'+id).empty().addClass('animated fadeIn').html(res);
                if(res == 'ok'){
                    $('.delIMGMes_'+img).detach();
                }

        },
        // если ошибка то выведем ошибку
        error: function (res) {
        }
    });
   // $(this).removeClass('all-text').addClass('hidden-text').html('Скрыть текст');
});
JS;

$this->registerJs($script);
?>