models/Games.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "games".
 *
 * @property int $id
 * @property string $title Название
 * @property int $cat Категория
 * @property string $date Дата выхода
 * @property string $url Ссылка
 * @property string $onedrive1 OneDrive
 * @property string $onedrive2 Зеркало OneDrive
 * @property string $gmirror1 Зеркало Google Drive 1
 * @property string $gmirror2 Зеркало Google Drive 2
 * @property string $untrimmed Необрезные
 * @property string $1f 1F
 * @property string $md5 Хеш сумма
 */
class Games extends \yii\db\ActiveRecord
{
    public $image;
    public $xlsx;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'games';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'cat', 'date', 'url'], 'required', 'on'=>'games'],
            [['cat'], 'integer'],
            [['onedrive1', 'onedrive2', 'gmirror1', 'gmirror2', 'untrimmed', 'f',  'md5', 'img', 'title'], 'safe'],
            [['title', 'url', 'onedrive1', 'onedrive2', 'gmirror1', 'gmirror2', 'untrimmed', 'f', 'md5', 'img'], 'string', 'max' => 255],
            [['image'], 'file', 'extensions' => 'png, jpg', 'skipOnEmpty' => true],
            [['xlsx'], 'file', 'extensions' => 'xlsx', 'skipOnEmpty' => true, 'on' => 'pars', 'checkExtensionByMimeType' => false],
            [['name',  'date', 'url'], 'safe' , 'on' => 'pars'],

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'title' => 'Название',
            'cat' => 'Категория',
            'date' => 'Дата выхода',
            'url' => 'Ссылка',
            'onedrive1' => 'OneDrive',
            'onedrive2' => 'Зеркало OneDrive',
            'gmirror1' => 'Зеркало Google Drive 1',
            'gmirror2' => 'Зеркало Google Drive 2',
            'untrimmed' => 'Необрезные',
            'f' => '1F',
            'md5' => 'Хеш сумма',
            'image' => 'Изображение',
            'xlsx' => 'xlsx файл',
        ];
    }


    public function uploadFile()
    {
        if ($this->validate())
        {
            $name = Yii::$app->getSecurity()->generateRandomString(32);
            $path ='file/' . $name . '.' . $this->xlsx->extension;
            $this->xlsx->saveAs($path, false);
            return $path;
        }
        else
        {
            return false;
        }
    }


}

controllers/GamesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Games;
use app\models\GamesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\User;
use yii\filters\AccessControl;


/**
 * GamesController implements the CRUD actions for Games model.
 */
class GamesController extends CastomController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                /*'only' => ['logout'],*/
                'rules' => [
                    /*[
                        // неавторизованному пользователю доступны только эти действия
                        'actions' => ['login', 'registration'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],*/
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['user'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post', 'get'],
                ],
            ],
        ];
    }

    /**
     * Lists all Games models.
     * @return mixed
     */
    public function actionIndex()
    {

        $this->setMeta('Игры');

        $user = User::find()->where(['id' => Yii::$app->user->id])->one();

        if(Yii::$app->user->isGuest){
            return $this->redirect('site/login');
        }elseif($user->invite == 0){
            Yii::$app->session->setFlash('info', 'Доступ в раздел запрещён Вы не купили инвайт!');
            return $this->redirect('/post/index');
        }

        //$this->layout = 'site';
        $searchModel = new GamesSearch();



        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'user' => $user,
        ]);
    }

    /**
     * Displays a single Games model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
            'pagination' => [
                'pageSize' => 30,
            ],
        ]);
    }

    /**
     * Creates a new Games model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Games();
        $model->scenario = 'games';
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Games model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->scenario = 'games';
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Games model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Games model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Games the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Games::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/games/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Games */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="games-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'cat')->textInput() ?>

    <?= $form->field($model, 'date')->textInput() ?>

    <?= $form->field($model, 'url')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'onedrive1')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'onedrive2')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'gmirror1')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'gmirror2')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'untrimmed')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'f')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'md5')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/games/_list.php
<?php
/**
 * Created by PhpStorm.
 * User: Mirol
 * Date: 23.02.2019
 * Time: 23:22
 */
use yii\helpers\Url;
use yii\helpers\Html;
?>

<div class="col-md-6 col-sm-6">
    <div class="friend-card">
        <?php if(isset($model->img)): ?>
            <img src="../<?= $model->img ?>" alt="<?= $model->name?>" class="img-responsive cover" />
        <?php else : ?>
            <img src="../images/Untitled-1.png" alt="<?= $model->title?>" class="img-responsive cover" />
        <?php endif; ?>
        <div class="card-info">
            <!--<img src="http://placehold.it/300x300" alt="user" class="profile-photo-lg" />-->
            <div class="friend-info">
                <!--<a href="#" class="pull-right text-green">My Friend</a>-->
                <h5><?= Yii::$app->params['gamesCat'][$model->cat] ?></h5>
                <p><a href="<?= Url::to(['games/view', 'id' => $model->id]) ?>" class="profile-link"><?= \app\controllers\CastomController::name($model->title) ?></a></p>
            </div>
        </div>
    </div>
</div>

views/games/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\GamesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="games-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'cat') ?>

    <?= $form->field($model, 'date') ?>

    <?= $form->field($model, 'url') ?>

    <?php // echo $form->field($model, 'onedrive1') ?>

    <?php // echo $form->field($model, 'onedrive2') ?>

    <?php // echo $form->field($model, 'gmirror1') ?>

    <?php // echo $form->field($model, 'gmirror2') ?>

    <?php // echo $form->field($model, 'untrimmed') ?>

    <?php // echo $form->field($model, '1f') ?>

    <?php // echo $form->field($model, 'md5') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/games/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Games */

//$this->title = 'Create Games';
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="games-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/games/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ListView;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $searchModel app\models\GamesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

/*$this->title = 'Games';*/
$this->params['breadcrumbs'][] = $this->title;
?>


<?= ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_list',
]);?>

views/games/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Games */

$this->title = 'Редоктировать: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="games-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/games/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use app\controllers\CastomController;

/* @var $this yii\web\View */
/* @var $model app\models\Games */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Игры', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="games-view">

    <h1><?= Html::encode($this->title) ?></h1>
<?php if(Yii::$app->user->can('redactor')) :?>
    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы действительно хотите удалить игру?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?php endif;?>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'title',
            [
                'attribute' => 'cat',
                'value' => function ($data){
                    return Yii::$app->params['cat'][$data->cat];
                },
                'format' => 'html',
                /*'filter'=>Yii::$app->params['cat'],*/
                /*'headerOptions' => ['width' => '200'],*/
            ],
           /* 'date',*/
            [
                'attribute' => 'url',
                'value' => function ($data){
                    if($data->url != null){
                        return '<a href="'.$data->url.'"><i class="glyphicon glyphicon-download-alt"></i></a>';
                    }else{
                        return '';
                    }
                },
                'format' => 'html',
                'filter' => false,
            ],
            [
                'attribute' => 'onedrive1',
                'value' => function ($data){
                    if($data->onedrive1 != null){
                        return '<a href="'.$data->onedrive1.'"><i class="glyphicon glyphicon-download-alt"></i></a>';
                    }else{
                        return '';
                    }
                },
                'format' => 'html',
                'filter' => false,
            ],
            [
                'attribute' => 'onedrive2',
                'value' => function ($data){
                    if($data->onedrive2 != null){
                        return '<a href="'.$data->onedrive2.'"><i class="glyphicon glyphicon-download-alt"></i></a>';
                    }else{
                        return '';
                    }
                },
                'format' => 'html',
                'filter' => false,
            ],
            [
                'attribute' => 'gmirror1',
                'value' => function ($data){
                    if($data->gmirror1 != null){
                        return '<a href="'.$data->gmirror1.'"><i class="glyphicon glyphicon-download-alt"></i></a>';
                    }else{
                        return '';
                    }
                },
                'format' => 'html',
                'filter' => false,
            ],
            [
                'attribute' => 'gmirror2',
                'value' => function ($data){
                    if($data->gmirror2 != null){
                        return '<a href="'.$data->gmirror2.'"><i class="glyphicon glyphicon-download-alt"></i></a>';
                    }else{
                        return '';
                    }
                },
                'format' => 'html',
                'filter' => false,
            ],
            [
                'attribute' => 'untrimmed',
                'value' => function ($data){
                    if($data->untrimmed != null){
                        return '<a href="'.$data->untrimmed.'"><i class="glyphicon glyphicon-download-alt"></i></a>';
                    }else{
                        return '';
                    }
                },
                'format' => 'html',
                'filter' => false,
            ],
            [
                'attribute' => 'f',
                'value' => function ($data){
                    if($data->f != null){
                        return '<a href="'.$data->f.'"><i class="glyphicon glyphicon-download-alt"></i></a>';
                    }else{
                        return '';
                    }
                },
                'format' => 'html',
                'filter' => false,
            ],
            'md5',
            [
                'attribute' => 'Описание',
                'value' => function ($data){
                    return '<a href="https://www.nintendo.ru/-/--299117.html?q='.CastomController::name($data->title).'&f=147393" target="_blank">'.CastomController::name($data->title).'</a>';
                },
                'format' => 'raw',
                'filter' => false,
            ]
        ],
    ]) ?>

</div>